ui: UI-related issues
frontend: frontend-related issues
design: design-related discussions
ux: user experience-related issues
visual: visual aspects of the project
component: component-related issues
layout: layout-related issues
style: styling-related discussions
responsive: responsive design issues